version: "3.9"

services:
  nosqldb:
    build:
      context: ./docker/nosqldb
      args:
        DK_UID: ${DK_UID}
        DK_GID: ${DK_GID}
    container_name: "${DK_PROJECT_NAME}-nosqldb"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME}
      MONGODB_REPLICA_SET_MODE: ${MONGODB_REPLICA_SET_MODE}
      MONGODB_ROOT_USER: ${MONGODB_ROOT_USER}
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_REPLICA_SET_KEY: ${MONGODB_REPLICA_SET_KEY}
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    # volumes:
    #   - "${MONGODB_VOLUME}:/bitnami/mongodb"
    networks:
      - zuvia_test

  api:
    build:
      context: .
      args:
        DK_UID: ${DK_UID}
        DK_GID: ${DK_GID}
    container_name: "${DK_PROJECT_NAME}-api"
    environment:
      NODE_ENV: ${DK_ENV}
      API_PORT: ${API_PORT:-3333}
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}"
    volumes:
      - "${PWD}:/home/node/project"
    networks:
      - zuvia_test
    depends_on:
      nosqldb:
        condition: service_started
    command: [ "npm", "run", "dev_docker" ]

networks:
  zuvia_test:
    driver: bridge
