version: "3.9"

services:
  nosqldb:
    build:
      context: ./docker/nosqldb
      args:
        DK_UID: ${DK_UID}
        DK_GID: ${DK_GID}
        NOSQLDB_INITDB_DATABASES: ${NOSQLDB_INITDB_DATABASES}
    container_name: "${DK_PROJECT_NAME}-nosqldb"
    ports:
      - "${NOSQLDB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${NOSQLDB_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${NOSQLDB_INITDB_ROOT_PASSWORD}
    volumes:
      - "${NOSQLDB_VOLUME}:/data/db"
    networks:
      - zuvia_test

  api:
    build:
      context: .
      args:
        DK_UID: ${DK_UID}
        DK_GID: ${DK_GID}
    container_name: "${DK_PROJECT_NAME}-api"
    environment:
      NODE_ENV: ${DK_ENV}
      API_PORT: ${API_PORT:-3333}
      MONGO_HOST: ${NOSQLDB_HOST}
      MONGO_PORT: ${NOSQLDB_PORT:-27017}
      MONGO_USERNAME: ${NOSQLDB_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${NOSQLDB_INITDB_ROOT_PASSWORD}
      MONGO_DATABASE: ${NOSQLDB_DATABASE}
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}"
    volumes:
      - "${PWD}:/home/node/project"
    networks:
      - zuvia_test
    depends_on:
      nosqldb:
        condition: service_started
    command: [ "npm", "run", "dev" ]

networks:
  zuvia_test:
    driver: bridge
